routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if (Auth::check())
    	return Redirect::to('/home');
    else
    	return Redirect::to('/login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group( ['middleware' => ['auth']], function() {

	Route::resource('users', 'UserController');

	Route::get('/templates/{id}/send-email', 'TemplateController@sendEmail')->name('templates.send_email');
	Route::post('/templates/send-email', 'TemplateController@postSendEmail')->name('templates.send_email.post');
	Route::resource('templates', 'TemplateController');

	Route::post('/queue/attempt/{id?}', 'QueueController@attempt')->name('queue.attempt');
	Route::resource('queue', 'QueueController', ['only' => [ 'index', 'destroy' ]]);

});

resources/views/template/_form.blade.php
<!-- Name Form Input -->
<div class="form-group @if ($errors->has('name')) has-error @endif">
    {!! Form::label('name', 'Nome') !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Name']) !!}
    @if ($errors->has('name')) <p class="form-text text-muted">{{ $errors->first('name') }}</p> @endif
</div>

<!-- Subject Form Input -->
<div class="form-group @if ($errors->has('subject')) has-error @endif">
    {!! Form::label('subject', 'Assunto') !!}
    {!! Form::text('subject', null, ['class' => 'form-control', 'placeholder' => 'Subject']) !!}
    @if ($errors->has('subject')) <p class="form-text text-muted">{{ $errors->first('subject') }}</p> @endif
</div>

<!-- Body Form Input -->
<div class="form-group @if ($errors->has('body')) has-error @endif">
    {!! Form::label('body', 'Conteúdo') !!}
    {!! Form::textarea('body', null, ['class' => 'form-control', 'placeholder' => 'Body']) !!}
    @if ($errors->has('body')) <p class="form-text text-muted">{{ $errors->first('body') }}</p> @endif
</div>

resources/views/template/_form_send.blade.php
<!-- Name Form Input -->
<div class="form-group">
    {!! Form::label('name', 'Nome') !!}
    <br />
    {{ $template->name }}
</div>

<!-- Subject Form Input -->
<div class="form-group">
    {!! Form::label('subject', 'Assunto') !!}
    <br />
    {{ $template->subject }}
</div>

<!-- Body Form Input -->
<div class="form-group">
    {!! Form::label('body', 'Conteúdo') !!}
    <br />
    {!! $template->body !!}
</div>

<!-- email Form Input -->
<div class="form-group @if ($errors->has('email')) has-error @endif">
    {!! Form::label('email', 'Destinatário') !!}
    {!! Form::email('email', null, ['class' => 'form-control', 'placeholder' => 'E-mail']) !!}
    {!! Form::hidden('template_id', $template->template_id) !!}
    @if ($errors->has('email')) <p class="form-text text-muted">{{ $errors->first('email') }}</p> @endif
</div>

resources/views/template/edit.blade.php
@extends('layouts.master')

@section('title', 'Editar template - ' . $template->name)

@section('content')

    <div class="row">
        <div class="col-md-5">
            <h3>Editar - {{ $template->name }}</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            <a href="{{ route('templates.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Voltar</a>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        {!! Form::model($template, ['method' => 'PUT', 'route' => ['templates.update',  $template->template_id ] ]) !!}
                            @include('template._form')
                            <!-- Submit Form Button -->
                            {!! Form::submit('Salvar', ['class' => 'btn btn-sm btn-voll']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/template/index.blade.php
@extends('layouts.master')

@section('title', 'Templates')

@section('content')

    <div class="row">
        <div class="col-md-5">
            <h3 class="modal-title">{{ $result->total() }} template(s)</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            @can('add_templates')
                <a href="{{ route('templates.create') }}" class="btn btn-voll btn-sm"> <i class="glyphicon glyphicon-plus-sign"></i> Novo</a>
            @endcan
        </div>
    </div>

    <div class="result-set">
        <table class="table table-bordered table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Subject</th>
                <th>Created By</th>
                <th>Created At</th>
                @can('edit_templates', 'delete_templates')
                <th class="text-center">Actions</th>
                @endcan
            </tr>
            </thead>
            <tbody>
            @foreach($result as $item)
                <tr>
                    <td>{{ $item->template_id }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->subject }}</td>
                    <td>{{ $item->create_user->name }}</td>
                    <td>{{ $item->created_at->format('d/m/Y H:i:s') }}</td>

                    @can('edit_templates')
                    <td class="text-center">
                        @include('shared._actions', [
                            'entity' => 'templates',
                            'id' => $item->template_id
                        ])
                    </td>
                    @endcan
                </tr>
            @endforeach
            </tbody>
        </table>

        <div class="text-center">
            {{ $result->links() }}
        </div>
    </div>

@endsection

resources/views/template/new.blade.php
@extends('layouts.master')

@section('title', 'Cadastrar template')

@section('content')

    <div class="row">
        <div class="col-md-5">
            <h3>Cadastrar template</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            <a href="{{ route('templates.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Voltar</a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {!! Form::open(['route' => ['templates.store'] ]) !!}
                @include('template._form')
                <!-- Submit Form Button -->
                {!! Form::submit('Salvar', ['class' => 'btn btn-sm btn-voll']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/template/send_email.blade.php
@extends('layouts.master')

@section('title', 'Enviar template - ' . $template->name)

@section('content')

    <div class="row">
        <div class="col-md-5">
            <h3>Enviar - {{ $template->name }}</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            <a href="{{ route('templates.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Voltar</a>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        {!! Form::model($template, ['method' => 'POST', 'route' => 'templates.send_email.post' ]) !!}
                            @include('template._form_send')
                            <!-- Submit Form Button -->
                            {!! Form::submit('Enviar', ['class' => 'btn btn-sm btn-voll']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection