routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if (Auth::check())
    	return Redirect::to('/home');
    else
    	return Redirect::to('/login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group( ['middleware' => ['auth']], function() {

	Route::resource('users', 'UserController');

	Route::get('/templates/{id}/send-email', 'TemplateController@sendEmail')->name('templates.send_email');
	Route::post('/templates/send-email', 'TemplateController@postSendEmail')->name('templates.send_email.post');
	Route::resource('templates', 'TemplateController');

	Route::post('/queue/attempt/{id?}', 'QueueController@attempt')->name('queue.attempt');
	Route::resource('queue', 'QueueController', ['only' => [ 'index', 'destroy' ]]);

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\Traits\Authorizable;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Template;

class User extends Authenticatable
{
    use Notifiable;
    use Authorizable;
    use HasRoles;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    /**
     * The primary key from table.
     *
     * @var array
     */
    protected $primaryKey = 'user_id';


    /**
     * The attributes with default value.
     *
     * @var array
     */
    protected $attributes = [
        'is_active' => 1,
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];


    public function create_templates()
    {
      return $this->hasMany(Template::class, 'created_user_id');
    }

    public function update_templates()
    {
      return $this->hasMany(Template::class, 'updated_user_id');
    }

    public function delete_templates()
    {
      return $this->hasMany(Template::class, 'deleted_user_id');
    }


    public function create_queues()
    {
      return $this->hasMany(Queue::class, 'created_user_id');
    }

    public function attempt_queues()
    {
      return $this->hasMany(Queue::class, 'attempt_user_id');
    }

    public function delete_queues()
    {
      return $this->hasMany(Queue::class, 'deleted_user_id');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;
use App\Http\Controllers\Controller;
use App\Http\Resources\UserResource;

class UserController extends Controller
{
	public function index()
	{
		$users = User::all();
		return UserResource::collection($users);
	}

	public function show($id)
	{
		$user = User::findOrFail($id);
		return new UserResource($user);
	}
 
    public function store(Request $request)
    {
        $user = $request->isMethod('put') ? User::findOrFail($request->user_id) : new Task;
            
        $user->user_id = $request->input('user_id');
        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->is_active = $request->input('is_active');
 
        if($user->save()) {
            return new UserResource($user);
        }
    }

    public function destroy($id)
    {
        $user = User::findOrfail($id); 
        if($user->delete()) {
            return new UserResource($user);
        } 
 
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;

class UserController extends Controller
{
	public function index()
	{
		$result = User::latest()->paginate();
		return view('user.index', compact('result'));
	}

	public function create()
	{
		$roles = Role::pluck('name', 'id');
		return view('user.new', compact('roles'));
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'name' => 'bail|required|min:2',
			'email' => 'required|email|unique:users',
			'password' => 'required|min:6',
			'roles' => 'required|min:1'
		]);

		// hash password
		$request->merge(['password' => bcrypt($request->get('password'))]);

		// Create the user
		if ( $user = User::create($request->except('roles', 'permissions')) ) {
			$this->syncPermissions($request, $user);
			flash('User has been created.');
		} else {
			flash()->error('Unable to create user.');
		}

		return redirect()->route('users.index');
	}

	public function edit($id)
	{
		$user = User::find($id);
		$roles = Role::pluck('name', 'id');
		$permissions = Permission::all('name', 'id');

		return view('user.edit', compact('user', 'roles', 'permissions'));
	}

	public function update(Request $request, $id)
	{

		$this->validate($request, [
			'name' => 'bail|required|min:2',
			'email' => 'required|email|unique:users,email,' . $id . ',user_id',
			'roles' => 'required|min:1'
		]);

		// Get the user
		$user = User::findOrFail($id);

		// Update user
		$user->fill($request->except('roles', 'permissions', 'password'));

		// check for password change
		if($request->get('password')) {
			$user->password = bcrypt($request->get('password'));
		}

		// Handle the user roles
		$this->syncPermissions($request, $user);

		$user->save();
		flash()->success('User has been updated.');
		return redirect()->route('users.index');
	}

	public function destroy($id)
	{
		if ( Auth::user()->id == $id ) {
			flash()->warning('Deletion of currently logged in user is not allowed :(')->important();
			return redirect()->back();
		}

		if( User::findOrFail($id)->delete() ) {
			flash()->success('User has been deleted');
		} else {
			flash()->success('User not deleted');
		}

		return redirect()->back();
	}

	private function syncPermissions(Request $request, $user)
	{
		// Get the submitted roles
		$roles = $request->get('roles', []);
		$permissions = $request->get('permissions', []);

		// Get the roles
		$roles = Role::find($roles);

		// check for current role changes
		if( ! $user->hasAllRoles( $roles ) ) {
			// reset all direct permissions for user
			$user->permissions()->sync([]);
		} else {
			// handle permissions
			$user->syncPermissions($permissions);
		}

		$user->syncRoles($roles);
		return $user;
	}
}

resources/views/user/_form.blade.php
<!-- Name Form Input -->
<div class="form-group @if ($errors->has('name')) has-error @endif">
    {!! Form::label('name', 'Nome') !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nome']) !!}
    @if ($errors->has('name')) <p class="form-text text-muted">{{ $errors->first('name') }}</p> @endif
</div>

<!-- email Form Input -->
<div class="form-group @if ($errors->has('email')) has-error @endif">
    {!! Form::label('email', 'E-mail') !!}
    {!! Form::text('email', null, ['class' => 'form-control', 'placeholder' => 'E-mail']) !!}
    @if ($errors->has('email')) <p class="form-text text-muted">{{ $errors->first('email') }}</p> @endif
</div>

<!-- password Form Input -->
<div class="form-group @if ($errors->has('password')) has-error @endif">
    {!! Form::label('password', 'Senha') !!}
    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Senha']) !!}
    @if ($errors->has('password')) <p class="form-text text-muted">{{ $errors->first('password') }}</p> @endif
</div>

<!-- Roles Form Input -->
<div class="form-group @if ($errors->has('roles')) has-error @endif">
    {!! Form::label('roles[]', 'Grupo de permissões') !!}
    {!! Form::select('roles[]', $roles, isset($user) ? $user->roles->pluck('id')->toArray() : null,  ['class' => 'form-control', 'multiple']) !!}
    @if ($errors->has('roles')) <p class="form-text text-muted">{{ $errors->first('roles') }}</p> @endif
</div>

<!-- Permissions -->
@if(isset($user))
    @include('shared._permissions', ['expanded' => 'true', 'visibility' => 'no', 'model' => $user ])
@endif

resources/views/user/edit.blade.php
@extends('layouts.master')

@section('title', 'Editar usuário - ' . $user->name)

@section('content')

    <div class="row">
        <div class="col-md-5">
            <h3>Editar - {{ $user->name }}</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            <a href="{{ route('users.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Voltar</a>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        {!! Form::model($user, ['method' => 'PUT', 'route' => ['users.update',  $user->user_id ] ]) !!}
                            @include('user._form')
                            <!-- Submit Form Button -->
                            {!! Form::submit('Salvar', ['class' => 'btn btn-sm btn-voll']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.master')

@section('title', 'Usuários')

@section('content')

    <div class="row">
        <div class="col-md-5">
            <h3 class="modal-title">{{ $result->total() }} usuário(s)</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            @can('add_users')
                <a href="{{ route('users.create') }}" class="btn btn-voll btn-sm"> <i class="glyphicon glyphicon-plus-sign"></i> Novo</a>
            @endcan
        </div>
    </div>

    <div class="result-set">
        <table class="table table-bordered table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Created At</th>
                @can('edit_users', 'delete_users')
                <th class="text-center">Actions</th>
                @endcan
            </tr>
            </thead>
            <tbody>
            @foreach($result as $item)
                <tr>
                    <td>{{ $item->user_id }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->email }}</td>
                    <td>{{ $item->roles->implode('name', ', ') }}</td>
                    <td>{{ $item->created_at->format('d/m/Y H:i:s') }}</td>

                    @can('edit_users')
                    <td class="text-center">
                        @include('shared._actions', [
                            'entity' => 'users',
                            'id' => $item->user_id
                        ])
                    </td>
                    @endcan
                </tr>
            @endforeach
            </tbody>
        </table>

        <div class="text-center">
            {{ $result->links() }}
        </div>
    </div>

@endsection

resources/views/user/new.blade.php
@extends('layouts.master')

@section('title', 'Cadastrar usuário')

@section('content')

    <div class="row">
        <div class="col-md-5">
            <h3>Cadastrar usuário</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            <a href="{{ route('users.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Voltar</a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {!! Form::open(['route' => ['users.store'] ]) !!}
                @include('user._form')
                <!-- Submit Form Button -->
                {!! Form::submit('Salvar', ['class' => 'btn btn-sm btn-voll']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection